{
    'name': 'FreightBox - Ocean Freight Reimagined',
    'category': 'FreightBox',
    'description': """
    """,
    'author': 'PowerpBox IT Solutions Pvt Ltd',
    'depends': ['base', 'web', 'crm', 'sale', 'sale_crm', 'sale_management', 'purchase',
                'account', 'website', 'mail', 'stock', 'portal', 'freightbox_contracts',  'fb_base',
                'base_freightbox'],
    'website': 'https://www.powerpbox.org/',
    'version': '1.0',
    'license': 'OPL-1',
    'images': [
        'static/description/banner.gif',
        'static/src/img/index_file_images/FreightBox_Full_Flow.gif',
        'static/src/img/correct.png',
        'static/src/img/index_file_images/tnt.png',
        'static/src/img/index_file_images/video_tutorial.png',
    ],
    # 'external_dependencies': {"python": ['pdfrw']},
    'data': [
        'security/ir.model.access.csv',
        'security/multi_company_security.xml',
        'security/user_security.xml',
        'data/mode_data.xml',
        'data/user_template_data.xml',
        'data/route_template_data.xml',
        'data/transport_template_data.xml',
        'data/ir_cron_data.xml',
        'data/freight_decimal_data.xml',
        'data/service_type_data.xml',
        'data/location_type_data.xml',
        'data/api_data.xml',
        'data/si_template_data.xml',
        'data/bol_template_data.xml',
        'data/crm_data.xml',
        'data/system_pera_data.xml',
        'data/ir_cron_data.xml',
        'wizard/shipment_quote.xml',
        'wizard/mail_wiz_view.xml',
        'wizard/rate_comparison.xml',
        'wizard/service_view_wiz.xml',
        'wizard/route_wiz_view.xml',
        'wizard/account_move_wiz.xml',
        'wizard/transport_template_wiz_view.xml',
        'wizard/facility_code_wiz_view.xml',
        'wizard/si_template_wiz.xml',
        'wizard/bol_templates_wiz_view.xml',
        'wizard/res_config_settings_views.xml',
        'wizard/trace_confirm_wizard_view.xml',
        'wizard/track_transport_wizard_view.xml',
        # 'wizard/blacklist_wiz_view.xml',
        # 'wizard/partner_kyc_wiz_view.xml',
        'wizard/unblacklist_wiz_view.xml',
        'wizard/add_api_calls_confirmation_wizard_view.xml',
        # 'wizard/company_kyc_wiz_view.xml',
        'wizard/print_sign.xml',
        'report/paper_formate.xml',
        'report/shipment_quote_template.xml',
        'report/shipment_quote_report.xml',
        'report/report_invoice_templates.xml',
        'report/sale_report_inherit.xml',
        'report/inherit_po_report.xml',
        'report/purchase_report_inherit.xml',
        'report/purchase_quotation_inherit.xml',
        'report/bill_of_lading_template.xml',
        'report/bill_of_lading_report.xml',
        'report/shipping_instruction_report.xml',
        'report/shipping_instruction_template.xml',
        'report/purchase_order_report.xml',
        'report/purchase_quotation_report.xml',
        'report/sale_order_report.xml',
        'report/work_order_report.xml',
        'report/work_order_template.xml',
        'report/damco_bill_of_lading_report.xml',
        'view/vessel_schedule_portal.xml',
        'view/bill_of_lading.xml',
        'view/product_view.xml',
        'view/mode_view.xml',
        'view/move_type_view.xml',
        'view/route_view.xml',
        'view/website_dashboard_view.xml',
        'view/unloc_view.xml',
        'view/container_type_view.xml',
        'view/account_incoterms_view.xml',
        'view/ir_sequence_view.xml',
        'view/booking_website.xml',
        'view/crm_lead_view.xml',
        'view/shipment_quote_view.xml',
        'view/request_for_quote_view.xml',
        'view/res_partner_view.xml',
        'view/purchase_view.xml',
        'view/charges_view.xml',
        'view/sale_view.xml',
        'view/job_view.xml',
        'view/home.xml',
        'view/freight_dashboard_view.xml',
        'view/user_templates_view.xml',
        'view/transport_view.xml',
        'view/shipping_instruction.xml',
        'view/si_templates_view.xml',
        'view/bol_templates_view.xml',
        'view/service_view.xml',
        'view/api.xml',
        'view/track_trace_portal.xml',
        'view/track_trace_event_view.xml',
        'view/tnt_dashboard_view.xml',
        'view/transport_template_view.xml',
        'view/account_move_view.xml',
        'view/portal_bol_edit.xml',
        'view/shipping_instruction_portal.xml',
        'view/shipping_instruction_update.xml',
        'view/vessel_tracking_views.xml',
        'view/res_users.xml',
        'view/vessel_location_track_views.xml',
        'view/signature_auth.xml',
        'view/portal_view.xml',
        'view/mrg_view.xml',
        'view/menu_view.xml',
        'view/portal_invoice.xml',
        'data/mail_template_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'freightbox/static/src/js/freight_box_dashboard.js',
            'freightbox/static/src/scss/track_trace_event_dashboard.scss',
            'freightbox/static/src/js/track_trace_event_dashboard.js',
            'freightbox/static/src/scss/rc_dashboard.scss',
            'freightbox/static/src/scss/sq_dashboard.scss',
            'freightbox/static/src/scss/job_dashboard.scss',
            'freightbox/static/src/scss/res_partner_dashboard.scss',
            'freightbox/static/src/scss/bol_dashboard.scss',
            'freightbox/static/src/scss/crm_dashboard.scss',
            # 'freightbox/static/src/scss/user_dashboard.scss',
            'freightbox/static/src/js/crm_dashboard.js',
            'freightbox/static/src/js/rc_dashboard.js',
            'freightbox/static/src/js/sq_dashboard.js',
            'freightbox/static/src/js/job_dashboard.js',
            'freightbox/static/src/js/res_partner_dashboard.js',
            'freightbox/static/src/js/bol_dashboard.js',
            # 'freightbox/static/src/js/user_dashboard.js',
            # 'freightbox/static/src/js/user_dashboard_kanban_controller.js',

            "freightbox//static/src/xml/crm_dashboard.xml",
            "freightbox//static/src/xml/shipment_quote_dashboard.xml",
            "freightbox/static/src/xml/rc_dashboard.xml",
            "freightbox/static/src/xml/track_trace_event_dashboard.xml",
            "freightbox/static/src/xml/job_dashboard.xml",
            "freightbox/static/src/xml/res_partner_dashboard.xml",
            "freightbox/static/src/xml/bol_dashboard.xml",
            "freightbox/static/src/xml/freight_box_dashboard_template.xml",

        ],
        'web.assets_qweb' : [
            "freightbox/static/src/xml/SiPopup.xml",
            "freightbox/static/src/xml/SiUpdatePopup.xml",
        ],
        'web.assets_frontend': [
            'freightbox/static/src/css/dashboard_portal.css',
            'freightbox/static/src/scss/home.scss',
            'https://kit.fontawesome.com/128ecf7e3d.js',
            'freightbox/static/src/js/website_booking.js',
            'freightbox/static/src/js/create_bol.js',
            'freightbox/static/src/js/shipping_instruction.js',
            'freightbox/static/src/js/shipping_instruction_update.js',
            'freightbox/static/src/js/track_trace.js',
            'freightbox/static/src/js/vessel_tracking.js',
            'freightbox/static/src/js/track_trace_portal.js',
            # 'freightbox/static/src/js/track_trace_standalone.js',
            'freightbox/static/src/js/signature_auth.js',
        ],
        
    },
    'post_init_hook': 'create_api_integration',
    'uninstall_hook': 'uninstall_hook',
    'price': 2999.00,
    'currency': 'USD',
}
