# -*- coding: utf-8 -*-
from odoo import api, fields, models, _


class BolTemplateWiz(models.Model):
    _name = 'bol.templates.wiz'
    _description = "BOL Template Wizard"

    name = fields.Char(string='Name', required=True)
    bol_id = fields.Many2one('si.templates', string='Shipping Instruction')
    created_from_bol = fields.Boolean("Created from BOL")

    def action_create_bol_template(self):
        BOL_obj = self.env['bill.of.lading']
        bol_rec = BOL_obj.browse([(self._context['current_id'])])
        bol_template_rec = self.env['bol.templates'].create({
            'name': self.name,
            'transport_document_type_code': bol_rec.transport_document_type_code,
            'is_shipped_onboard_type': bol_rec.is_shipped_onboard_type,
            'number_of_originals': bol_rec.number_of_originals,
            'number_of_copies': bol_rec.number_of_copies,
            'pre_carriage_under_shippers_responsibility': bol_rec.pre_carriage_under_shippers_responsibility,
            'is_electronic': bol_rec.is_electronic,
            'carrier_booking_reference': bol_rec.carrier_booking_reference,
            'is_charges_displayed': bol_rec.is_charges_displayed,
            'location_name': bol_rec.location_name,
            'un_location_code': bol_rec.un_location_code,
            'city_name': bol_rec.city_name,
            'state_region': bol_rec.state_region,
            'country': bol_rec.country,
            # 'si_user_id': self.env.user.id,
            'shipping_instruction_ID': bol_rec.shipping_instruction_ID,
            'transport_document_reference': bol_rec.transport_document_reference,
            'shipped_onboard_date': bol_rec.shipped_onboard_date,
            'terms_and_conditions': bol_rec.terms_and_conditions,
            'reciept_or_deliverytype_at_origin': bol_rec.reciept_or_deliverytype_at_origin,
            'reciept_or_deliverytype_at_dest': bol_rec.reciept_or_deliverytype_at_dest,
            'cargo_movement_type_at_origin': bol_rec.cargo_movement_type_at_origin,
            'cargo_movement_type_at_dest': bol_rec.cargo_movement_type_at_dest,
            'issue_date': bol_rec.issue_date,
            'poi_location_name': bol_rec.poi_location_name,
            'poi_un_location_code': bol_rec.poi_un_location_code,
            'poi_street_name': bol_rec.poi_street_name,
            'poi_street_number': bol_rec.poi_street_number,
            'poi_floor': bol_rec.poi_floor,
            'poi_post_code': bol_rec.poi_post_code,
            'poi_city_name': bol_rec.poi_city_name,
            'poi_state_region': bol_rec.poi_state_region,
            'poi_country': bol_rec.poi_country,
            'received_for_shipment_date': bol_rec.received_for_shipment_date,
            'service_contract_reference': bol_rec.service_contract_reference,
            'declared_value': bol_rec.declared_value,
            'declared_value_currency': bol_rec.declared_value_currency,
            'issuer_code': bol_rec.issuer_code,
            'issuer_code_list_provider': bol_rec.issuer_code_list_provider,
            'no_of_rider_pages': bol_rec.no_of_rider_pages,
            'document_hash': bol_rec.document_hash,
            'planned_arrival_date': bol_rec.planned_arrival_date,
            'planned_departure_date': bol_rec.planned_departure_date,
            'pre_carried_by': bol_rec.pre_carried_by,
            'por_location_name': bol_rec.por_location_name,
            'por_un_location_code': bol_rec.por_un_location_code,
            'por_street_name': bol_rec.por_street_name,
            'por_street_number': bol_rec.por_street_number,
            'por_floor': bol_rec.por_floor,
            'por_post_code': bol_rec.por_post_code,
            'por_city_name': bol_rec.por_city_name,
            'por_state_region': bol_rec.por_state_region,
            'por_country': bol_rec.por_country,
            'pol_location_name': bol_rec.pol_location_name,
            'pol_un_location_code': bol_rec.pol_un_location_code,
            'pol_city_name': bol_rec.pol_city_name,
            'pol_state_region': bol_rec.pol_state_region,
            'pol_country': bol_rec.pol_country,
            'pod_location_name': bol_rec.pod_location_name,
            'pod_un_location_code': bol_rec.pod_un_location_code,
            'pod_city_name': bol_rec.pod_city_name,
            'pod_state_region': bol_rec.pod_state_region,
            'pod_country': bol_rec.pod_country,
            'plod_location_name': bol_rec.plod_location_name,
            'plod_un_location_code': bol_rec.plod_un_location_code,
            'plod_street_name': bol_rec.plod_street_name,
            'plod_street_number': bol_rec.plod_street_number,
            'plod_floor': bol_rec.plod_floor,
            'plod_post_code': bol_rec.plod_post_code,
            'plod_city_name': bol_rec.plod_city_name,
            'plod_state_region': bol_rec.plod_state_region,
            'plod_country': bol_rec.plod_country,
            'oir_location_name': bol_rec.oir_location_name,
            'oir_un_location_code': bol_rec.oir_un_location_code,
            'oir_street_name': bol_rec.oir_street_name,
            'oir_street_number': bol_rec.oir_street_number,
            'oir_floor': bol_rec.oir_floor,
            'oir_post_code': bol_rec.oir_post_code,
            'oir_city_name': bol_rec.oir_city_name,
            'oir_state_region': bol_rec.oir_state_region,
            'oir_country': bol_rec.oir_country,
            'pre_location_name': bol_rec.pre_location_name,
            'pre_latitude': bol_rec.pre_latitude,
            'pre_longitude': bol_rec.pre_longitude,
            'pre_un_location_code': bol_rec.pre_un_location_code,
            'pre_street_name': bol_rec.pre_street_name,
            'pre_street_number': bol_rec.pre_street_number,
            'pre_floor': bol_rec.pre_floor,
            'pre_post_code': bol_rec.pre_post_code,
            'pre_city_name': bol_rec.pre_city_name,
            'pre_state_region': bol_rec.pre_state_region,
            'pre_country': bol_rec.pre_country,
        })
        return bol_template_rec
